name: Auto merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == "dependabot[bot]" }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-request: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    step:
      - uses: actions/checkout@v4
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
